// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="snn_infer_snn_infer,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.016000,HLS_SYN_LAT=23611,HLS_SYN_TPT=none,HLS_SYN_MEM=20,HLS_SYN_DSP=0,HLS_SYN_FF=1808,HLS_SYN_LUT=3094,HLS_VERSION=2022_2}" *)

module snn_infer (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_state1 = 22'd1;
parameter    ap_ST_fsm_state2 = 22'd2;
parameter    ap_ST_fsm_state3 = 22'd4;
parameter    ap_ST_fsm_state4 = 22'd8;
parameter    ap_ST_fsm_state5 = 22'd16;
parameter    ap_ST_fsm_state6 = 22'd32;
parameter    ap_ST_fsm_state7 = 22'd64;
parameter    ap_ST_fsm_state8 = 22'd128;
parameter    ap_ST_fsm_state9 = 22'd256;
parameter    ap_ST_fsm_state10 = 22'd512;
parameter    ap_ST_fsm_state11 = 22'd1024;
parameter    ap_ST_fsm_state12 = 22'd2048;
parameter    ap_ST_fsm_state13 = 22'd4096;
parameter    ap_ST_fsm_state14 = 22'd8192;
parameter    ap_ST_fsm_state15 = 22'd16384;
parameter    ap_ST_fsm_state16 = 22'd32768;
parameter    ap_ST_fsm_state17 = 22'd65536;
parameter    ap_ST_fsm_state18 = 22'd131072;
parameter    ap_ST_fsm_state19 = 22'd262144;
parameter    ap_ST_fsm_state20 = 22'd524288;
parameter    ap_ST_fsm_state21 = 22'd1048576;
parameter    ap_ST_fsm_state22 = 22'd2097152;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [3:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] input_r_address0;
reg input_r_ce0;
reg[3:0] output_r_address0;
reg output_r_ce0;
reg output_r_we0;
reg[31:0] output_r_d0;

(* fsm_encoding = "none" *) reg   [21:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_start;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_done;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_idle;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_ready;
wire   [9:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_input_r_address0;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_input_r_ce0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_sum_out;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_sum_out_ap_vld;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_954_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_954_p_din1;
wire   [1:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_954_p_opcode;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_954_p_ce;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_958_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_958_p_din1;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_958_p_ce;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_start;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_done;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_idle;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_ready;
wire   [9:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_input_r_address0;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_input_r_ce0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_sum_2_out;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_sum_2_out_ap_vld;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_954_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_954_p_din1;
wire   [1:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_954_p_opcode;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_954_p_ce;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_958_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_958_p_din1;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_958_p_ce;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_start;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_done;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_idle;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_ready;
wire   [9:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_input_r_address0;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_input_r_ce0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_sum_4_out;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_sum_4_out_ap_vld;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_954_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_954_p_din1;
wire   [1:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_954_p_opcode;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_954_p_ce;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_958_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_958_p_din1;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_958_p_ce;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_start;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_done;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_idle;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_ready;
wire   [9:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_input_r_address0;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_input_r_ce0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_sum_6_out;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_sum_6_out_ap_vld;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_954_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_954_p_din1;
wire   [1:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_954_p_opcode;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_954_p_ce;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_958_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_958_p_din1;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_958_p_ce;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_start;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_done;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_idle;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_ready;
wire   [9:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_input_r_address0;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_input_r_ce0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_sum_8_out;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_sum_8_out_ap_vld;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_954_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_954_p_din1;
wire   [1:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_954_p_opcode;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_954_p_ce;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_958_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_958_p_din1;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_958_p_ce;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_start;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_done;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_idle;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_ready;
wire   [9:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_input_r_address0;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_input_r_ce0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_sum_10_out;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_sum_10_out_ap_vld;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_954_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_954_p_din1;
wire   [1:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_954_p_opcode;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_954_p_ce;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_958_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_958_p_din1;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_958_p_ce;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_start;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_done;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_idle;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_ready;
wire   [9:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_input_r_address0;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_input_r_ce0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_sum_12_out;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_sum_12_out_ap_vld;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_954_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_954_p_din1;
wire   [1:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_954_p_opcode;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_954_p_ce;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_958_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_958_p_din1;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_958_p_ce;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_start;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_done;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_idle;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_ready;
wire   [9:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_input_r_address0;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_input_r_ce0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_sum_14_out;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_sum_14_out_ap_vld;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_954_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_954_p_din1;
wire   [1:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_954_p_opcode;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_954_p_ce;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_958_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_958_p_din1;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_958_p_ce;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_start;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_done;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_idle;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_ready;
wire   [9:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_input_r_address0;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_input_r_ce0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_sum_16_out;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_sum_16_out_ap_vld;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_954_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_954_p_din1;
wire   [1:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_954_p_opcode;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_954_p_ce;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_958_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_958_p_din1;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_958_p_ce;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_start;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_done;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_idle;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_ready;
wire   [9:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_input_r_address0;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_input_r_ce0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_sum_18_out;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_sum_18_out_ap_vld;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_954_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_954_p_din1;
wire   [1:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_954_p_opcode;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_954_p_ce;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_958_p_din0;
wire   [31:0] grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_958_p_din1;
wire    grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_958_p_ce;
reg    grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg    grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg    grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_start_reg;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
reg    grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_start_reg;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
reg    grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_start_reg;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state21;
wire   [31:0] select_ln26_fu_369_p3;
wire   [31:0] select_ln26_1_fu_423_p3;
wire   [31:0] select_ln26_2_fu_477_p3;
wire   [31:0] select_ln26_3_fu_531_p3;
wire   [31:0] select_ln26_4_fu_585_p3;
wire   [31:0] select_ln26_5_fu_639_p3;
wire   [31:0] select_ln26_6_fu_693_p3;
wire   [31:0] select_ln26_7_fu_747_p3;
wire   [31:0] select_ln26_8_fu_801_p3;
wire   [31:0] select_ln26_9_fu_855_p3;
reg   [31:0] grp_fu_319_p0;
wire   [31:0] bitcast_ln26_fu_328_p1;
wire   [7:0] tmp_fu_331_p4;
wire   [22:0] trunc_ln26_fu_341_p1;
wire   [0:0] icmp_ln26_1_fu_351_p2;
wire   [0:0] icmp_ln26_fu_345_p2;
wire   [0:0] or_ln26_fu_357_p2;
wire   [0:0] grp_fu_319_p2;
wire   [0:0] and_ln26_fu_363_p2;
wire   [31:0] bitcast_ln26_1_fu_382_p1;
wire   [7:0] tmp_2_fu_385_p4;
wire   [22:0] trunc_ln26_1_fu_395_p1;
wire   [0:0] icmp_ln26_3_fu_405_p2;
wire   [0:0] icmp_ln26_2_fu_399_p2;
wire   [0:0] or_ln26_1_fu_411_p2;
wire   [0:0] and_ln26_1_fu_417_p2;
wire   [31:0] bitcast_ln26_2_fu_436_p1;
wire   [7:0] tmp_4_fu_439_p4;
wire   [22:0] trunc_ln26_2_fu_449_p1;
wire   [0:0] icmp_ln26_5_fu_459_p2;
wire   [0:0] icmp_ln26_4_fu_453_p2;
wire   [0:0] or_ln26_2_fu_465_p2;
wire   [0:0] and_ln26_2_fu_471_p2;
wire   [31:0] bitcast_ln26_3_fu_490_p1;
wire   [7:0] tmp_6_fu_493_p4;
wire   [22:0] trunc_ln26_3_fu_503_p1;
wire   [0:0] icmp_ln26_7_fu_513_p2;
wire   [0:0] icmp_ln26_6_fu_507_p2;
wire   [0:0] or_ln26_3_fu_519_p2;
wire   [0:0] and_ln26_3_fu_525_p2;
wire   [31:0] bitcast_ln26_4_fu_544_p1;
wire   [7:0] tmp_8_fu_547_p4;
wire   [22:0] trunc_ln26_4_fu_557_p1;
wire   [0:0] icmp_ln26_9_fu_567_p2;
wire   [0:0] icmp_ln26_8_fu_561_p2;
wire   [0:0] or_ln26_4_fu_573_p2;
wire   [0:0] and_ln26_4_fu_579_p2;
wire   [31:0] bitcast_ln26_5_fu_598_p1;
wire   [7:0] tmp_s_fu_601_p4;
wire   [22:0] trunc_ln26_5_fu_611_p1;
wire   [0:0] icmp_ln26_11_fu_621_p2;
wire   [0:0] icmp_ln26_10_fu_615_p2;
wire   [0:0] or_ln26_5_fu_627_p2;
wire   [0:0] and_ln26_5_fu_633_p2;
wire   [31:0] bitcast_ln26_6_fu_652_p1;
wire   [7:0] tmp_11_fu_655_p4;
wire   [22:0] trunc_ln26_6_fu_665_p1;
wire   [0:0] icmp_ln26_13_fu_675_p2;
wire   [0:0] icmp_ln26_12_fu_669_p2;
wire   [0:0] or_ln26_6_fu_681_p2;
wire   [0:0] and_ln26_6_fu_687_p2;
wire   [31:0] bitcast_ln26_7_fu_706_p1;
wire   [7:0] tmp_13_fu_709_p4;
wire   [22:0] trunc_ln26_7_fu_719_p1;
wire   [0:0] icmp_ln26_15_fu_729_p2;
wire   [0:0] icmp_ln26_14_fu_723_p2;
wire   [0:0] or_ln26_7_fu_735_p2;
wire   [0:0] and_ln26_7_fu_741_p2;
wire   [31:0] bitcast_ln26_8_fu_760_p1;
wire   [7:0] tmp_15_fu_763_p4;
wire   [22:0] trunc_ln26_8_fu_773_p1;
wire   [0:0] icmp_ln26_17_fu_783_p2;
wire   [0:0] icmp_ln26_16_fu_777_p2;
wire   [0:0] or_ln26_8_fu_789_p2;
wire   [0:0] and_ln26_8_fu_795_p2;
wire   [31:0] bitcast_ln26_9_fu_814_p1;
wire   [7:0] tmp_17_fu_817_p4;
wire   [22:0] trunc_ln26_9_fu_827_p1;
wire   [0:0] icmp_ln26_19_fu_837_p2;
wire   [0:0] icmp_ln26_18_fu_831_p2;
wire   [0:0] or_ln26_9_fu_843_p2;
wire   [0:0] and_ln26_9_fu_849_p2;
reg    grp_fu_319_ce;
wire   [31:0] grp_fu_954_p2;
reg   [31:0] grp_fu_954_p0;
reg   [31:0] grp_fu_954_p1;
reg    grp_fu_954_ce;
wire   [31:0] grp_fu_958_p2;
reg   [31:0] grp_fu_958_p0;
reg   [31:0] grp_fu_958_p1;
reg    grp_fu_958_ce;
reg   [21:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
reg    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 22'd1;
#0 grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_start_reg = 1'b0;
#0 grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_start_reg = 1'b0;
#0 grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_start_reg = 1'b0;
#0 grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_start_reg = 1'b0;
#0 grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_start_reg = 1'b0;
#0 grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_start_reg = 1'b0;
#0 grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_start_reg = 1'b0;
#0 grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_start_reg = 1'b0;
#0 grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_start_reg = 1'b0;
#0 grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_start_reg = 1'b0;
end

snn_infer_snn_infer_Pipeline_VITIS_LOOP_20_2 grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_start),
    .ap_done(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_done),
    .ap_idle(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_idle),
    .ap_ready(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_ready),
    .input_r_address0(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_input_r_address0),
    .input_r_ce0(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_input_r_ce0),
    .input_r_q0(input_r_q0),
    .sum_out(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_sum_out),
    .sum_out_ap_vld(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_sum_out_ap_vld),
    .grp_fu_954_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_954_p_din0),
    .grp_fu_954_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_954_p_din1),
    .grp_fu_954_p_opcode(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_954_p_opcode),
    .grp_fu_954_p_dout0(grp_fu_954_p2),
    .grp_fu_954_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_954_p_ce),
    .grp_fu_958_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_958_p_din0),
    .grp_fu_958_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_958_p_din1),
    .grp_fu_958_p_dout0(grp_fu_958_p2),
    .grp_fu_958_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_958_p_ce)
);

snn_infer_snn_infer_Pipeline_VITIS_LOOP_20_21 grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_start),
    .ap_done(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_done),
    .ap_idle(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_idle),
    .ap_ready(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_ready),
    .input_r_address0(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_input_r_address0),
    .input_r_ce0(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_input_r_ce0),
    .input_r_q0(input_r_q0),
    .sum_2_out(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_sum_2_out),
    .sum_2_out_ap_vld(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_sum_2_out_ap_vld),
    .grp_fu_954_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_954_p_din0),
    .grp_fu_954_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_954_p_din1),
    .grp_fu_954_p_opcode(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_954_p_opcode),
    .grp_fu_954_p_dout0(grp_fu_954_p2),
    .grp_fu_954_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_954_p_ce),
    .grp_fu_958_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_958_p_din0),
    .grp_fu_958_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_958_p_din1),
    .grp_fu_958_p_dout0(grp_fu_958_p2),
    .grp_fu_958_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_958_p_ce)
);

snn_infer_snn_infer_Pipeline_VITIS_LOOP_20_22 grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_start),
    .ap_done(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_done),
    .ap_idle(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_idle),
    .ap_ready(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_ready),
    .input_r_address0(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_input_r_address0),
    .input_r_ce0(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_input_r_ce0),
    .input_r_q0(input_r_q0),
    .sum_4_out(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_sum_4_out),
    .sum_4_out_ap_vld(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_sum_4_out_ap_vld),
    .grp_fu_954_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_954_p_din0),
    .grp_fu_954_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_954_p_din1),
    .grp_fu_954_p_opcode(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_954_p_opcode),
    .grp_fu_954_p_dout0(grp_fu_954_p2),
    .grp_fu_954_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_954_p_ce),
    .grp_fu_958_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_958_p_din0),
    .grp_fu_958_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_958_p_din1),
    .grp_fu_958_p_dout0(grp_fu_958_p2),
    .grp_fu_958_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_958_p_ce)
);

snn_infer_snn_infer_Pipeline_VITIS_LOOP_20_23 grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_start),
    .ap_done(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_done),
    .ap_idle(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_idle),
    .ap_ready(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_ready),
    .input_r_address0(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_input_r_address0),
    .input_r_ce0(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_input_r_ce0),
    .input_r_q0(input_r_q0),
    .sum_6_out(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_sum_6_out),
    .sum_6_out_ap_vld(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_sum_6_out_ap_vld),
    .grp_fu_954_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_954_p_din0),
    .grp_fu_954_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_954_p_din1),
    .grp_fu_954_p_opcode(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_954_p_opcode),
    .grp_fu_954_p_dout0(grp_fu_954_p2),
    .grp_fu_954_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_954_p_ce),
    .grp_fu_958_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_958_p_din0),
    .grp_fu_958_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_958_p_din1),
    .grp_fu_958_p_dout0(grp_fu_958_p2),
    .grp_fu_958_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_958_p_ce)
);

snn_infer_snn_infer_Pipeline_VITIS_LOOP_20_24 grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_start),
    .ap_done(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_done),
    .ap_idle(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_idle),
    .ap_ready(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_ready),
    .input_r_address0(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_input_r_address0),
    .input_r_ce0(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_input_r_ce0),
    .input_r_q0(input_r_q0),
    .sum_8_out(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_sum_8_out),
    .sum_8_out_ap_vld(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_sum_8_out_ap_vld),
    .grp_fu_954_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_954_p_din0),
    .grp_fu_954_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_954_p_din1),
    .grp_fu_954_p_opcode(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_954_p_opcode),
    .grp_fu_954_p_dout0(grp_fu_954_p2),
    .grp_fu_954_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_954_p_ce),
    .grp_fu_958_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_958_p_din0),
    .grp_fu_958_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_958_p_din1),
    .grp_fu_958_p_dout0(grp_fu_958_p2),
    .grp_fu_958_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_958_p_ce)
);

snn_infer_snn_infer_Pipeline_VITIS_LOOP_20_25 grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_start),
    .ap_done(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_done),
    .ap_idle(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_idle),
    .ap_ready(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_ready),
    .input_r_address0(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_input_r_address0),
    .input_r_ce0(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_input_r_ce0),
    .input_r_q0(input_r_q0),
    .sum_10_out(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_sum_10_out),
    .sum_10_out_ap_vld(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_sum_10_out_ap_vld),
    .grp_fu_954_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_954_p_din0),
    .grp_fu_954_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_954_p_din1),
    .grp_fu_954_p_opcode(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_954_p_opcode),
    .grp_fu_954_p_dout0(grp_fu_954_p2),
    .grp_fu_954_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_954_p_ce),
    .grp_fu_958_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_958_p_din0),
    .grp_fu_958_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_958_p_din1),
    .grp_fu_958_p_dout0(grp_fu_958_p2),
    .grp_fu_958_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_958_p_ce)
);

snn_infer_snn_infer_Pipeline_VITIS_LOOP_20_26 grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_start),
    .ap_done(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_done),
    .ap_idle(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_idle),
    .ap_ready(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_ready),
    .input_r_address0(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_input_r_address0),
    .input_r_ce0(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_input_r_ce0),
    .input_r_q0(input_r_q0),
    .sum_12_out(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_sum_12_out),
    .sum_12_out_ap_vld(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_sum_12_out_ap_vld),
    .grp_fu_954_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_954_p_din0),
    .grp_fu_954_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_954_p_din1),
    .grp_fu_954_p_opcode(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_954_p_opcode),
    .grp_fu_954_p_dout0(grp_fu_954_p2),
    .grp_fu_954_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_954_p_ce),
    .grp_fu_958_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_958_p_din0),
    .grp_fu_958_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_958_p_din1),
    .grp_fu_958_p_dout0(grp_fu_958_p2),
    .grp_fu_958_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_958_p_ce)
);

snn_infer_snn_infer_Pipeline_VITIS_LOOP_20_27 grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_start),
    .ap_done(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_done),
    .ap_idle(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_idle),
    .ap_ready(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_ready),
    .input_r_address0(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_input_r_address0),
    .input_r_ce0(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_input_r_ce0),
    .input_r_q0(input_r_q0),
    .sum_14_out(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_sum_14_out),
    .sum_14_out_ap_vld(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_sum_14_out_ap_vld),
    .grp_fu_954_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_954_p_din0),
    .grp_fu_954_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_954_p_din1),
    .grp_fu_954_p_opcode(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_954_p_opcode),
    .grp_fu_954_p_dout0(grp_fu_954_p2),
    .grp_fu_954_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_954_p_ce),
    .grp_fu_958_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_958_p_din0),
    .grp_fu_958_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_958_p_din1),
    .grp_fu_958_p_dout0(grp_fu_958_p2),
    .grp_fu_958_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_958_p_ce)
);

snn_infer_snn_infer_Pipeline_VITIS_LOOP_20_28 grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_start),
    .ap_done(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_done),
    .ap_idle(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_idle),
    .ap_ready(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_ready),
    .input_r_address0(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_input_r_address0),
    .input_r_ce0(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_input_r_ce0),
    .input_r_q0(input_r_q0),
    .sum_16_out(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_sum_16_out),
    .sum_16_out_ap_vld(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_sum_16_out_ap_vld),
    .grp_fu_954_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_954_p_din0),
    .grp_fu_954_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_954_p_din1),
    .grp_fu_954_p_opcode(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_954_p_opcode),
    .grp_fu_954_p_dout0(grp_fu_954_p2),
    .grp_fu_954_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_954_p_ce),
    .grp_fu_958_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_958_p_din0),
    .grp_fu_958_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_958_p_din1),
    .grp_fu_958_p_dout0(grp_fu_958_p2),
    .grp_fu_958_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_958_p_ce)
);

snn_infer_snn_infer_Pipeline_VITIS_LOOP_20_29 grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_start),
    .ap_done(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_done),
    .ap_idle(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_idle),
    .ap_ready(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_ready),
    .input_r_address0(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_input_r_address0),
    .input_r_ce0(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_input_r_ce0),
    .input_r_q0(input_r_q0),
    .sum_18_out(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_sum_18_out),
    .sum_18_out_ap_vld(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_sum_18_out_ap_vld),
    .grp_fu_954_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_954_p_din0),
    .grp_fu_954_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_954_p_din1),
    .grp_fu_954_p_opcode(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_954_p_opcode),
    .grp_fu_954_p_dout0(grp_fu_954_p2),
    .grp_fu_954_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_954_p_ce),
    .grp_fu_958_p_din0(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_958_p_din0),
    .grp_fu_958_p_din1(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_958_p_din1),
    .grp_fu_958_p_dout0(grp_fu_958_p2),
    .grp_fu_958_p_ce(grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_958_p_ce)
);

snn_infer_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U51(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_319_p0),
    .din1(32'd0),
    .ce(grp_fu_319_ce),
    .opcode(5'd2),
    .dout(grp_fu_319_p2)
);

snn_infer_fadd_32ns_32ns_32_4_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_4_no_dsp_1_U52(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_954_p0),
    .din1(grp_fu_954_p1),
    .ce(grp_fu_954_ce),
    .dout(grp_fu_954_p2)
);

snn_infer_fmul_32ns_32ns_32_3_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_3_max_dsp_1_U53(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_958_p0),
    .din1(grp_fu_958_p1),
    .ce(grp_fu_958_ce),
    .dout(grp_fu_958_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_start_reg <= 1'b1;
        end else if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_ready == 1'b1)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_start_reg <= 1'b1;
        end else if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_ready == 1'b1)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_start_reg <= 1'b1;
        end else if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_ready == 1'b1)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_start_reg <= 1'b1;
        end else if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_ready == 1'b1)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_start_reg <= 1'b1;
        end else if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_ready == 1'b1)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_start_reg <= 1'b1;
        end else if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_ready == 1'b1)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_start_reg <= 1'b1;
        end else if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_ready == 1'b1)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state17)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_start_reg <= 1'b1;
        end else if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_ready == 1'b1)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state19)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_start_reg <= 1'b1;
        end else if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_ready == 1'b1)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_start_reg <= 1'b1;
        end else if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_ready == 1'b1)) begin
            grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_start_reg <= 1'b0;
        end
    end
end

always @ (*) begin
    if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

assign ap_ST_fsm_state17_blk = 1'b0;

always @ (*) begin
    if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_done == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_done == 1'b0)) begin
        ap_ST_fsm_state20_blk = 1'b1;
    end else begin
        ap_ST_fsm_state20_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2) | ((grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_done == 1'b0) & (1'b1 == ap_CS_fsm_state20)) | ((grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_done == 1'b0) & (1'b1 == ap_CS_fsm_state18)) | ((grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_done == 1'b0) & (1'b1 == ap_CS_fsm_state6)) | ((grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_done == 1'b0) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == ap_CS_fsm_state16) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_done == 1'b0)) | ((1'b1 == ap_CS_fsm_state14) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_done == 1'b0)) | ((1'b1 == ap_CS_fsm_state12) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_done == 1'b0)) | ((1'b1 == ap_CS_fsm_state10) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_done == 1'b0)) | ((1'b1 == ap_CS_fsm_state8) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_done == 1'b0)))) begin
        grp_fu_319_ce = 1'b0;
    end else begin
        grp_fu_319_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_319_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_sum_18_out;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        grp_fu_319_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_sum_16_out;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_319_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_sum_14_out;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        grp_fu_319_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_sum_12_out;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_319_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_sum_10_out;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_fu_319_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_sum_8_out;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_319_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_sum_6_out;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_319_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_sum_4_out;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_319_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_sum_2_out;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_319_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_sum_out;
    end else begin
        grp_fu_319_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_954_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_954_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_954_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_954_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_954_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_954_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_954_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_954_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_954_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_954_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_954_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_954_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_954_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_954_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_954_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_954_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_954_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_954_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_954_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_954_p_ce;
    end else begin
        grp_fu_954_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_954_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_954_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_954_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_954_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_954_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_954_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_954_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_954_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_954_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_954_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_954_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_954_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_954_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_954_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_954_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_954_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_954_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_954_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_954_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_954_p_din0;
    end else begin
        grp_fu_954_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_954_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_954_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_954_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_954_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_954_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_954_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_954_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_954_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_954_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_954_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_954_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_954_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_954_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_954_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_954_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_954_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_954_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_954_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_954_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_954_p_din1;
    end else begin
        grp_fu_954_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_958_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_958_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_958_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_958_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_958_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_958_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_958_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_958_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_958_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_958_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_958_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_958_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_958_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_958_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_958_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_958_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_958_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_958_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_958_ce = grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_958_p_ce;
    end else begin
        grp_fu_958_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_958_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_958_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_958_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_958_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_958_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_958_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_958_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_958_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_958_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_958_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_958_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_958_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_958_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_958_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_958_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_958_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_958_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_958_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_958_p0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_958_p_din0;
    end else begin
        grp_fu_958_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        grp_fu_958_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_grp_fu_958_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_fu_958_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_grp_fu_958_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        grp_fu_958_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_grp_fu_958_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_958_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_grp_fu_958_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_958_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_grp_fu_958_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_958_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_grp_fu_958_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_958_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_grp_fu_958_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_958_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_grp_fu_958_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_958_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_grp_fu_958_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_958_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_grp_fu_958_p_din1;
    end else begin
        grp_fu_958_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        input_r_address0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        input_r_address0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        input_r_address0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        input_r_address0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        input_r_address0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        input_r_address0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        input_r_address0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        input_r_address0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_address0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_input_r_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_r_address0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_input_r_address0;
    end else begin
        input_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        input_r_ce0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        input_r_ce0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        input_r_ce0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        input_r_ce0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        input_r_ce0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        input_r_ce0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        input_r_ce0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        input_r_ce0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        input_r_ce0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_input_r_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        input_r_ce0 = grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_input_r_ce0;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        output_r_address0 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        output_r_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        output_r_address0 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        output_r_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        output_r_address0 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        output_r_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        output_r_address0 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        output_r_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_r_address0 = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_r_address0 = 64'd0;
    end else begin
        output_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | ((grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20)) | ((grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | ((grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == ap_CS_fsm_state16) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state14) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state12) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state10) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state8) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_done == 1'b1)))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        output_r_d0 = select_ln26_9_fu_855_p3;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        output_r_d0 = select_ln26_8_fu_801_p3;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        output_r_d0 = select_ln26_7_fu_747_p3;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        output_r_d0 = select_ln26_6_fu_693_p3;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        output_r_d0 = select_ln26_5_fu_639_p3;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        output_r_d0 = select_ln26_4_fu_585_p3;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        output_r_d0 = select_ln26_3_fu_531_p3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        output_r_d0 = select_ln26_2_fu_477_p3;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_r_d0 = select_ln26_1_fu_423_p3;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        output_r_d0 = select_ln26_fu_369_p3;
    end else begin
        output_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state22) | ((grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20)) | ((grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | ((grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((1'b1 == ap_CS_fsm_state16) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state14) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state12) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state10) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state8) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_done == 1'b1)))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_CS_fsm_state10) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((1'b1 == ap_CS_fsm_state16) & (grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            if (((grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state20))) begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln26_1_fu_417_p2 = (or_ln26_1_fu_411_p2 & grp_fu_319_p2);

assign and_ln26_2_fu_471_p2 = (or_ln26_2_fu_465_p2 & grp_fu_319_p2);

assign and_ln26_3_fu_525_p2 = (or_ln26_3_fu_519_p2 & grp_fu_319_p2);

assign and_ln26_4_fu_579_p2 = (or_ln26_4_fu_573_p2 & grp_fu_319_p2);

assign and_ln26_5_fu_633_p2 = (or_ln26_5_fu_627_p2 & grp_fu_319_p2);

assign and_ln26_6_fu_687_p2 = (or_ln26_6_fu_681_p2 & grp_fu_319_p2);

assign and_ln26_7_fu_741_p2 = (or_ln26_7_fu_735_p2 & grp_fu_319_p2);

assign and_ln26_8_fu_795_p2 = (or_ln26_8_fu_789_p2 & grp_fu_319_p2);

assign and_ln26_9_fu_849_p2 = (or_ln26_9_fu_843_p2 & grp_fu_319_p2);

assign and_ln26_fu_363_p2 = (or_ln26_fu_357_p2 & grp_fu_319_p2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign bitcast_ln26_1_fu_382_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_sum_2_out;

assign bitcast_ln26_2_fu_436_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_sum_4_out;

assign bitcast_ln26_3_fu_490_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_sum_6_out;

assign bitcast_ln26_4_fu_544_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_sum_8_out;

assign bitcast_ln26_5_fu_598_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_sum_10_out;

assign bitcast_ln26_6_fu_652_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_sum_12_out;

assign bitcast_ln26_7_fu_706_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_sum_14_out;

assign bitcast_ln26_8_fu_760_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_sum_16_out;

assign bitcast_ln26_9_fu_814_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_sum_18_out;

assign bitcast_ln26_fu_328_p1 = grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_sum_out;

assign grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_start = grp_snn_infer_Pipeline_VITIS_LOOP_20_21_fu_238_ap_start_reg;

assign grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_start = grp_snn_infer_Pipeline_VITIS_LOOP_20_22_fu_247_ap_start_reg;

assign grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_start = grp_snn_infer_Pipeline_VITIS_LOOP_20_23_fu_256_ap_start_reg;

assign grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_start = grp_snn_infer_Pipeline_VITIS_LOOP_20_24_fu_265_ap_start_reg;

assign grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_start = grp_snn_infer_Pipeline_VITIS_LOOP_20_25_fu_274_ap_start_reg;

assign grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_start = grp_snn_infer_Pipeline_VITIS_LOOP_20_26_fu_283_ap_start_reg;

assign grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_start = grp_snn_infer_Pipeline_VITIS_LOOP_20_27_fu_292_ap_start_reg;

assign grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_start = grp_snn_infer_Pipeline_VITIS_LOOP_20_28_fu_301_ap_start_reg;

assign grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_start = grp_snn_infer_Pipeline_VITIS_LOOP_20_29_fu_310_ap_start_reg;

assign grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_start = grp_snn_infer_Pipeline_VITIS_LOOP_20_2_fu_229_ap_start_reg;

assign icmp_ln26_10_fu_615_p2 = ((tmp_s_fu_601_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln26_11_fu_621_p2 = ((trunc_ln26_5_fu_611_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_12_fu_669_p2 = ((tmp_11_fu_655_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln26_13_fu_675_p2 = ((trunc_ln26_6_fu_665_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_14_fu_723_p2 = ((tmp_13_fu_709_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln26_15_fu_729_p2 = ((trunc_ln26_7_fu_719_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_16_fu_777_p2 = ((tmp_15_fu_763_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln26_17_fu_783_p2 = ((trunc_ln26_8_fu_773_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_18_fu_831_p2 = ((tmp_17_fu_817_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln26_19_fu_837_p2 = ((trunc_ln26_9_fu_827_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_1_fu_351_p2 = ((trunc_ln26_fu_341_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_2_fu_399_p2 = ((tmp_2_fu_385_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln26_3_fu_405_p2 = ((trunc_ln26_1_fu_395_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_4_fu_453_p2 = ((tmp_4_fu_439_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln26_5_fu_459_p2 = ((trunc_ln26_2_fu_449_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_6_fu_507_p2 = ((tmp_6_fu_493_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln26_7_fu_513_p2 = ((trunc_ln26_3_fu_503_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_8_fu_561_p2 = ((tmp_8_fu_547_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln26_9_fu_567_p2 = ((trunc_ln26_4_fu_557_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln26_fu_345_p2 = ((tmp_fu_331_p4 != 8'd255) ? 1'b1 : 1'b0);

assign or_ln26_1_fu_411_p2 = (icmp_ln26_3_fu_405_p2 | icmp_ln26_2_fu_399_p2);

assign or_ln26_2_fu_465_p2 = (icmp_ln26_5_fu_459_p2 | icmp_ln26_4_fu_453_p2);

assign or_ln26_3_fu_519_p2 = (icmp_ln26_7_fu_513_p2 | icmp_ln26_6_fu_507_p2);

assign or_ln26_4_fu_573_p2 = (icmp_ln26_9_fu_567_p2 | icmp_ln26_8_fu_561_p2);

assign or_ln26_5_fu_627_p2 = (icmp_ln26_11_fu_621_p2 | icmp_ln26_10_fu_615_p2);

assign or_ln26_6_fu_681_p2 = (icmp_ln26_13_fu_675_p2 | icmp_ln26_12_fu_669_p2);

assign or_ln26_7_fu_735_p2 = (icmp_ln26_15_fu_729_p2 | icmp_ln26_14_fu_723_p2);

assign or_ln26_8_fu_789_p2 = (icmp_ln26_17_fu_783_p2 | icmp_ln26_16_fu_777_p2);

assign or_ln26_9_fu_843_p2 = (icmp_ln26_19_fu_837_p2 | icmp_ln26_18_fu_831_p2);

assign or_ln26_fu_357_p2 = (icmp_ln26_fu_345_p2 | icmp_ln26_1_fu_351_p2);

assign select_ln26_1_fu_423_p3 = ((and_ln26_1_fu_417_p2[0:0] == 1'b1) ? bitcast_ln26_1_fu_382_p1 : 32'd0);

assign select_ln26_2_fu_477_p3 = ((and_ln26_2_fu_471_p2[0:0] == 1'b1) ? bitcast_ln26_2_fu_436_p1 : 32'd0);

assign select_ln26_3_fu_531_p3 = ((and_ln26_3_fu_525_p2[0:0] == 1'b1) ? bitcast_ln26_3_fu_490_p1 : 32'd0);

assign select_ln26_4_fu_585_p3 = ((and_ln26_4_fu_579_p2[0:0] == 1'b1) ? bitcast_ln26_4_fu_544_p1 : 32'd0);

assign select_ln26_5_fu_639_p3 = ((and_ln26_5_fu_633_p2[0:0] == 1'b1) ? bitcast_ln26_5_fu_598_p1 : 32'd0);

assign select_ln26_6_fu_693_p3 = ((and_ln26_6_fu_687_p2[0:0] == 1'b1) ? bitcast_ln26_6_fu_652_p1 : 32'd0);

assign select_ln26_7_fu_747_p3 = ((and_ln26_7_fu_741_p2[0:0] == 1'b1) ? bitcast_ln26_7_fu_706_p1 : 32'd0);

assign select_ln26_8_fu_801_p3 = ((and_ln26_8_fu_795_p2[0:0] == 1'b1) ? bitcast_ln26_8_fu_760_p1 : 32'd0);

assign select_ln26_9_fu_855_p3 = ((and_ln26_9_fu_849_p2[0:0] == 1'b1) ? bitcast_ln26_9_fu_814_p1 : 32'd0);

assign select_ln26_fu_369_p3 = ((and_ln26_fu_363_p2[0:0] == 1'b1) ? bitcast_ln26_fu_328_p1 : 32'd0);

assign tmp_11_fu_655_p4 = {{bitcast_ln26_6_fu_652_p1[30:23]}};

assign tmp_13_fu_709_p4 = {{bitcast_ln26_7_fu_706_p1[30:23]}};

assign tmp_15_fu_763_p4 = {{bitcast_ln26_8_fu_760_p1[30:23]}};

assign tmp_17_fu_817_p4 = {{bitcast_ln26_9_fu_814_p1[30:23]}};

assign tmp_2_fu_385_p4 = {{bitcast_ln26_1_fu_382_p1[30:23]}};

assign tmp_4_fu_439_p4 = {{bitcast_ln26_2_fu_436_p1[30:23]}};

assign tmp_6_fu_493_p4 = {{bitcast_ln26_3_fu_490_p1[30:23]}};

assign tmp_8_fu_547_p4 = {{bitcast_ln26_4_fu_544_p1[30:23]}};

assign tmp_fu_331_p4 = {{bitcast_ln26_fu_328_p1[30:23]}};

assign tmp_s_fu_601_p4 = {{bitcast_ln26_5_fu_598_p1[30:23]}};

assign trunc_ln26_1_fu_395_p1 = bitcast_ln26_1_fu_382_p1[22:0];

assign trunc_ln26_2_fu_449_p1 = bitcast_ln26_2_fu_436_p1[22:0];

assign trunc_ln26_3_fu_503_p1 = bitcast_ln26_3_fu_490_p1[22:0];

assign trunc_ln26_4_fu_557_p1 = bitcast_ln26_4_fu_544_p1[22:0];

assign trunc_ln26_5_fu_611_p1 = bitcast_ln26_5_fu_598_p1[22:0];

assign trunc_ln26_6_fu_665_p1 = bitcast_ln26_6_fu_652_p1[22:0];

assign trunc_ln26_7_fu_719_p1 = bitcast_ln26_7_fu_706_p1[22:0];

assign trunc_ln26_8_fu_773_p1 = bitcast_ln26_8_fu_760_p1[22:0];

assign trunc_ln26_9_fu_827_p1 = bitcast_ln26_9_fu_814_p1[22:0];

assign trunc_ln26_fu_341_p1 = bitcast_ln26_fu_328_p1[22:0];

endmodule //snn_infer
